### ISSUE TITLE
Implementation of `ForcedRollingHalfDisk` class that represents dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#534]
The following problems have to be checked or fixed, in order to ensure the correctness of implemented system:

- [x] checking if a class is executable,

- [x] validation of figures for schemes and real examples,

- [x] validation of reference parameters,

- [x] validation of random parameters,

- [x] validation of  description of  description of parameters,

- [x] validation of units.

**Comment by MichalKacperek** [comment]
The following problems have to be checked or fixed, in order to ensure the correctness of implemented system:

- [ ] checking if a class is executable,

- [ ] validation of figures for schemes and real examples,

- [ ] validation of reference parameters,

- [ ] validation of random parameters,

- [ ] validation of  description of  description of parameters,

- [ ] validation of units.

**Comment by MichalKacperek** [comment]
Done! Code was checked with the following call:
```
from dynpy.models.mechanics import ForcedRollingBar
from dynpy.utilities.documents.document import DynSysOverviewReport

DynSysOverviewReport(reported_object=ForcedRollingHalfDisk())
```
